"""remove cache vdb resource

Revision ID: 3c482922c304
Revises: f634e4c5e66f
Create Date: 2026-09-11 04:39:30.418800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c482922c304'
down_revision: Union[str, Sequence[str], None] = 'f634e4c5e66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cache_vdb_resources_status'), table_name='cache_vdb_resources')
    op.drop_index(op.f('ix_cache_vdb_resources_user_id'), table_name='cache_vdb_resources')
    op.drop_table('cache_vdb_resources')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_vdb_resources',
    sa.Column('cache_vdb_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'READY', 'FAILED', name='cachevdbstatus'), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('vdb_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('cache_vdb_resources_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_vdb_id', name=op.f('cache_vdb_resources_pkey'))
    )
    op.create_index(op.f('ix_cache_vdb_resources_user_id'), 'cache_vdb_resources', ['user_id'], unique=True)
    op.create_index(op.f('ix_cache_vdb_resources_status'), 'cache_vdb_resources', ['status'], unique=False)
    # ### end Alembic commands ###
