"""restore cache vdb resource

Revision ID: 77cc3ba82684
Revises: 3c482922c304
Create Date: 2026-09-11 04:56:05.150752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '77cc3ba82684'
down_revision: Union[str, Sequence[str], None] = '3c482922c304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_vdb_resources',
    sa.Column('cache_vdb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column(
    'status',
    postgresql.ENUM(
        'PENDING',
        'PROCESSING',
        'READY',
        'FAILED',
        name='cachevdbstatus',
        create_type=False
    ),
    nullable=False
),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vdb_path', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_vdb_id')
    )
    op.create_index(op.f('ix_cache_vdb_resources_status'), 'cache_vdb_resources', ['status'], unique=False)
    op.create_index(op.f('ix_cache_vdb_resources_user_id'), 'cache_vdb_resources', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cache_vdb_resources_user_id'), table_name='cache_vdb_resources')
    op.drop_index(op.f('ix_cache_vdb_resources_status'), table_name='cache_vdb_resources')
    op.drop_table('cache_vdb_resources')
    # ### end Alembic commands ###
