"""sync current database models

Revision ID: a09c0c0873f9
Revises: 77cc3ba82684
Create Date: 2026-10-03 13:33:56.460853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a09c0c0873f9'
down_revision: Union[str, Sequence[str], None] = '77cc3ba82684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('convo_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('starter_question', sa.Text(), nullable=False),
    sa.Column('starter_answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_convo_created_at_desc', 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('ltm_vdb_resources',
    sa.Column('ltm_vdb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='ltmvdbstatus'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vdb_path', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ltm_vdb_id')
    )
    op.create_index(op.f('ix_ltm_vdb_resources_status'), 'ltm_vdb_resources', ['status'], unique=False)
    op.create_index(op.f('ix_ltm_vdb_resources_user_id'), 'ltm_vdb_resources', ['user_id'], unique=True)
    op.add_column('ai_responses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('ai_responses', sa.Column('convo_id', sa.Text(), nullable=True))
    op.add_column('ai_responses', sa.Column('question', sa.Text(), nullable=False))
    op.add_column('ai_responses', sa.Column('ai_source', sa.String(length=20), nullable=False))
    op.add_column('ai_responses', sa.Column('from_tool', sa.Boolean(), nullable=True))
    op.alter_column('ai_responses', 'response_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(op.f('ai_responses_message_id_key'), 'ai_responses', type_='unique')
    op.create_index('idx_ai_responses_created_at_desc', 'ai_responses', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_ai_responses_user_id'), 'ai_responses', ['user_id'], unique=False)
    op.drop_constraint(op.f('ai_responses_message_id_fkey'), 'ai_responses', type_='foreignkey')
    op.create_foreign_key(None, 'ai_responses', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('ai_responses', 'message_id')
    op.drop_column('ai_responses', 'retrieved_chunks_count')
    op.drop_column('ai_responses', 'processing_time_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_responses', sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ai_responses', sa.Column('retrieved_chunks_count', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('ai_responses', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ai_responses', type_='foreignkey')
    op.create_foreign_key(op.f('ai_responses_message_id_fkey'), 'ai_responses', 'messages', ['message_id'], ['message_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ai_responses_user_id'), table_name='ai_responses')
    op.drop_index('idx_ai_responses_created_at_desc', table_name='ai_responses')
    op.create_unique_constraint(op.f('ai_responses_message_id_key'), 'ai_responses', ['message_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_responses', 'response_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('ai_responses', 'from_tool')
    op.drop_column('ai_responses', 'ai_source')
    op.drop_column('ai_responses', 'question')
    op.drop_column('ai_responses', 'convo_id')
    op.drop_column('ai_responses', 'user_id')
    op.drop_index(op.f('ix_ltm_vdb_resources_user_id'), table_name='ltm_vdb_resources')
    op.drop_index(op.f('ix_ltm_vdb_resources_status'), table_name='ltm_vdb_resources')
    op.drop_table('ltm_vdb_resources')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index('idx_ai_convo_created_at_desc', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
