"""add bm25_resources table

Revision ID: f1b4876f6c84
Revises: 80e71439ccf1
Create Date: 2026-08-26 03:15:41.462633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b4876f6c84'
down_revision: Union[str, Sequence[str], None] = '80e71439ccf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm25_resources',
    sa.Column('bm25_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', 'STALE', name='bm25status'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('index_path', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bm25_id')
    )
    op.create_index(op.f('ix_bm25_resources_status'), 'bm25_resources', ['status'], unique=False)
    op.create_index(op.f('ix_bm25_resources_user_id'), 'bm25_resources', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bm25_resources_user_id'), table_name='bm25_resources')
    op.drop_index(op.f('ix_bm25_resources_status'), table_name='bm25_resources')
    op.drop_table('bm25_resources')
    # ### end Alembic commands ###
