"""versions and many things status

Revision ID: f634e4c5e66f
Revises: f1b4876f6c84
Create Date: 2026-09-11 01:21:29.525015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f634e4c5e66f'
down_revision: Union[str, Sequence[str], None] = 'f1b4876f6c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_vdb_resources',
    sa.Column('cache_vdb_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='cachevdbstatus'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vdb_path', sa.String(length=512), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cache_vdb_id')
    )
    op.create_index(op.f('ix_cache_vdb_resources_status'), 'cache_vdb_resources', ['status'], unique=False)
    op.create_index(op.f('ix_cache_vdb_resources_user_id'), 'cache_vdb_resources', ['user_id'], unique=True)
    op.add_column('documents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'version')
    op.drop_index(op.f('ix_cache_vdb_resources_user_id'), table_name='cache_vdb_resources')
    op.drop_index(op.f('ix_cache_vdb_resources_status'), table_name='cache_vdb_resources')
    op.drop_table('cache_vdb_resources')
    # ### end Alembic commands ###
