from fastapi import status
from utils.APIResponce_error_code_enum import (
    USER_ERROR_CODES,
    SYSTEM_ERROR_CODES
)

ERROR_STATUS_MAP = {

    # User Errors
    USER_ERROR_CODES.EMPTY_INPUT.value:
        status.HTTP_400_BAD_REQUEST,

    USER_ERROR_CODES.UNSUPPORTED_INPUT.value:
        status.HTTP_400_BAD_REQUEST,

    USER_ERROR_CODES.PROMPT_INJECTION_DETECTED.value:
        status.HTTP_403_FORBIDDEN,

    USER_ERROR_CODES.INAPPROPRIATE_CONTENT.value:
        status.HTTP_403_FORBIDDEN,

    USER_ERROR_CODES.UNKNOWN_INPUT.value:
        status.HTTP_422_UNPROCESSABLE_ENTITY,


    # System Errors
    SYSTEM_ERROR_CODES.MY_QUOTA_REACHED.value:
        status.HTTP_429_TOO_MANY_REQUESTS,

    SYSTEM_ERROR_CODES.AI_SERVICE_FAILURE.value:
        status.HTTP_500_INTERNAL_SERVER_ERROR,

    SYSTEM_ERROR_CODES.AI_REPAIR_FAILURE.value:
        status.HTTP_500_INTERNAL_SERVER_ERROR,

    SYSTEM_ERROR_CODES.RAW_REPAIR_FAILURE.value:
        status.HTTP_500_INTERNAL_SERVER_ERROR,
}