import enum 
class USER_ERROR_CODES(enum.Enum):
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT"
    UNKNOWN_INPUT = "UNKNOWN_INPUT"
    UNSUPPORTED_FILE = "UNSUPPORTED_FILE"
    FILE_TOO_BIG = "FILE_TOO_BIG"
    INAPPROPRIATE_FILE = "INAPPROPRIATE_FILE"
    
    #auth:
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    
    
    #service:
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"

    #duplicate
    INPUT_ALREADY_EXISTS = "INPUT_ALREADY_EXISTS"
    DUPLICATE_FILE = "DUPLICATE_FILE"

class SYSTEM_ERROR_CODES(enum.Enum):
    #Ai related:
    MY_QUOTA_REACHED = "MY_QUOTA_REACHED"
    AI_SERVICE_FAILURE = "AI_SERVICE_FAILURE"
    AI_REPAIR_FAILURE = "AI_REPAIR_FAILURE" 
    RAW_REPAIR_FAILURE = "RAW_REPAIR_FAILURE"


    #App realted:
    
    
    
    #DB related:
    DATABASE_ERROR = "DATABASE_ERROR"
    
    
    #system:
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
    
    
    #redis:
    
    
    
    #redis-session-sets:
    NO_AVALIBLE_SESSIONS = "NO_AVALIBLE_SESSIONS"
    
    
    #celery workers:
    WORKER_PROCESS_FAILED = "WORKER_PROCESSED_FAILED"
    WORKER_PROCESS_RETRYING = "WORKER_PROCESSED_RETRYING"
    WORKER_IN_PROCESS = "WORKER_IN_PROCESS"
    
    
    #file uploading:
    FILE_UPLOAD_EXCEPTION = "FILE_UPLOAD_EXCEPTION"
    FILE_VALIDATION_FAILED = "FILE_VALIDATION_FAILED"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    SAVING_VALIDATED_FILE_EXCEPTION = "SAVING_VALIDATED_FILE_EXCEPTION"
    
    
    #bellow 3 taskes starter exception:
    TOKENIZATION_EXCEPTION = "TOKENIZATION_EXCEPTION"
    
    #prasing:
    FILE_PARSE_EXCEPTION = "FILE_PARSE_EXCEPTION"
    
    #chunking:
    FILE_CHUNKING_EXCEPTION = "FILE_CHUNKING_EXCEPTION"
    
    
    #embeding:
    FILE_EMBEDING_EXCEPTION = "FILE_EMBEDING_EXCEPTION"
    
    
    #worker input errors(upload):
    INVALID_TASK1_PAYLOAD = "INVALID_TASK1_PAYLOAD"
    INVALID_TASK2_PAYLOAD = "INVALID_TASK2_PAYLOAD"
    
    
    #task
    TASK_FAILED = "TASK_FAILED"
    
    
    #vectordb related:
    NO_RELATED_VECTOR_DATABASE_FOUND = "NO_RELATED_VECTOR_DATABASE_FOUND"
    
    
    #retriver realted:
    NO_DATA_FOUND_BY_RETRIVER = "NO_DATA_FOUND_BY_RETRIVER"
    
    
    #reranker
    NO_DATA_WAS_SENT_TO_RANKER = "NO_DATA_WAS_SENT_TO_RANKER"
    
    
    #retriver in hyde:
    HYDE_RETRIVER_FAILURE = "HYDE_RETRIVER_FAILURE"
    
    
    #RRF:
    RRF_FALIURE = "RRF_FALIURE"