import enum


class BaseLogEvent(enum.Enum):
    """
    Base class for all log event enums.
    Used as a common type hint across schemas (e.g., event: BaseLogEvent).
    """
    pass


class AuthLog(BaseLogEvent):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    JWT_VALIDATION_FAILED = "JWT_VALIDATION_FAILED"


class GatewayLog(BaseLogEvent):
    AI_REQUEST_RECEIVED = "AI_REQUEST_RECEIVED"
    AI_REQUEST_COLLISION = "AI_REQUEST_COLLISION"
    AI_QUOTA_EXHAUSTED = "AI_QUOTA_EXHAUSTED"


class ReservationLog(BaseLogEvent):
    AI_RESERVATION_CREATED = "AI_RESERVATION_CREATED"
    AI_RESERVATION_COMPLETED = "AI_RESERVATION_COMPLETED"
    AI_RESERVATION_FAILED = "AI_RESERVATION_FAILED"


class ServiceLog(BaseLogEvent):
    AI_SERVICE_STARTED = "AI_SERVICE_STARTED"
    AI_SERVICE_IN_PROCESSING = "AI_SERVICE_IN_PROCESSING"
    AI_SERVICE_COMPLETED = "AI_SERVICE_COMPLETED"
    AI_SERVICE_TERMINATED = "AI_SERVICE_TERMINATED"
    AI_SERVICE_FAILED = "AI_SERVICE_FAILED"
    AI_SERVICE_ENDED = "AI_SERVICE_ENDED"

    AI_MY_QUOTA_REACHED = "AI_MY_QUOTA_REACHED"
    EXITING_AI_SERVICE = "EXITING_AI_SERVICE"



class RetriverLog(BaseLogEvent):
    BUILDING_RETRIVER_STARTED = "BUILDING_RETRIVER_STARTED"
    
    FETCHING_DOCS_FOR_BM25 = "FETCHING_DOCS_FOR_BM25"
    COULD_NOT_FIND_DOCS_FOR_BM25 = "COULD_NOT_FIND_DOCS_FOR_BM25"
    COULD_NOT_CONVERT_DOCS_FOR_BM25 = "COULD_NOT_CONVERT_DOCS_FOR_BM25"
    
    BUILDING_RETRIVER_FAILURE = "BUILDING_RETRIVER_FAILURE"
    BUILDING_RETRIVER_SUCCESS = "BUILDING_RETRIVER_SUCCESS"
    EXITING_RETRIVER_BUILDER = "EXITING_RETRIVER_BUILDER"
    
    
    BUILDING_BM25 = "BUILDING_BM25"
    BUILDING_BM25_SUCCESS = "BUILDING_BM25_SUCCESS"
    BUILDING_BM25_FAILURE = "BUILDING_BM25_FAILURE"
    
    
    BUILDING_VECTOR_RETRIVER = "BUILDING_VECTOR_RETRIVER"
    BUILDING_VECTOR_RETRIVER_SUCCESS = "BUILDING_VECTOR_RETRIVER_SUCCESS"
    BUILDING_VECTOR_RETRIVER_FAILURE = "BUILDING_VECTOR_RETRIVER_FAILURE"

    RERANKER_FALLBACK_TO_HYBRID = "RERANKER_FALLBACK_TO_HYBRID"

    CREATING_HYBRID_RETRIVER = "CREATING_HYBRID_RETRIVER"
    CREATING_HYBRID_RETRIVER_FAILURE = "CREATING_HYBRID_RETRIVER_FAILURE"
    CREATING_HYBRID_RETRIVER_SUCCESS = "CREATING_HYBRID_RETRIVER_SUCCESS"
    
    
class ReRanklog(BaseLogEvent):
    
    VALIDATING_RERANK_RESULT_STARTED = "VALIDATING_RERANK_RESULT_STARTED"
    VALIDATING_RERANK_RESULT_FAILURE = "VALIDATING_RERANK_RESULT_FAILURE"
    VALIDATING_RERANK_RESULT_SUCCESS = "VALIDATING_RERANK_RESULT_SUCCESS"
    
    EXITING_VALIDATING_RERANK_FUNCTION = "EXITING_VALIDATING_RERANK_FUNCTION"
    
    CANDIDATE_IDS_MISMATCH = "CANDIDATE_IDS_MISMATCH"
    RELEVANCE_SCORES_NOT_DESCENDING = "RELEVANCE_SCORES_NOT_DESCENDING"
    RERANK_EVIDENCE_QUOTE_EMPTY = "RERANK_EVIDENCE_QUOTE_EMPTY"
    EVIDENCE_QUOTE_NOT_FOUND_IN_SOURCE = "EVIDENCE_QUOTE_NOT_FOUND_IN_SOURCE"

    RERANK_RESULT_VALIDATION_SUCCESS = "RERANK_RESULT_VALIDATION_SUCCESS"
    RERANK_RESULT_VALIDATION_FAILURE = "RERANK_RESULT_VALIDATION_FAILURE"

    EMPTY_RERANK_RESULT = "EMPTY_RERANK_RESULT"
    EMPTY_RANKED_CANDIDATES = "EMPTY_RANKED_CANDIDATES"

    DUPLICATE_CANDIDATE_IDS_DETECTED = "DUPLICATE_CANDIDATE_IDS_DETECTED"
    INVALID_CANDIDATE_IDS_DETECTED = "INVALID_CANDIDATE_IDS_DETECTED"

    INVALID_RELEVANCE_SCORE_ORDER = "INVALID_RELEVANCE_SCORE_ORDER"

    EMPTY_EVIDENCE_QUOTE_DETECTED = "EMPTY_EVIDENCE_QUOTE_DETECTED"
    INVALID_EVIDENCE_QUOTE_DETECTED = "INVALID_EVIDENCE_QUOTE_DETECTED"
    

class MappingReReankLog(BaseLogEvent):
    MAPPING_RERANKED_STARTED = "MAPPING_RERANKED_STARTED"
    MAPPING_RERANKED_FAILURE = "MAPPING_RERANKED_FAILURE"
    MAPPING_RERANKED_SUCCESS = "MAPPING_RERANKED_SUCCESS"
    EXITING_MAPPING_RERANKED_FUNCTION = "EXITING_MAPPING_RERANKED_FUNCTION"



#the middle man
class RetrievalStrategyLog(BaseLogEvent):
    RETRIEVAL_STRATEGY_STARTED = "RETRIEVAL_STRATEGY_STARTED"
    RETRIEVAL_STRATEGY_FAILED = "RETRIEVAL_STRATEGY_FAILED"
    RETRIEVAL_STRATEGY_SUCCESS = "RETRIEVAL_STRATEGY_SUCCESS"

    FALLING_BACK_TO_DEFAULT_ROUTE = "FALLING_BACK_TO_DEFAULT_ROUTE"

    EXECUTING_MULTI_INDEXING = "EXECUTING_MULTI_INDEXING"
    MULTI_INDEX_NOT_READY = "MULTI_INDEX_NOT_READY"
    MULTI_INDEX_EXECUTION_FAILED = "MULTI_INDEX_EXECUTION_FAILED"
    FALLING_BACK_TO_MULTI_QUERY = "FALLING_BACK_TO_MULTI_QUERY"

    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"

    EXITING_RETRIEVAL_STRATEGY = "EXITING_RETRIEVAL_STRATEGY"
    

class HyDELog(BaseLogEvent):
    HYDE_GENERATION_STARTED = "HYDE_GENERATION_STARTED"
    HYDE_GENERATION_FAILED = "HYDE_GENERATION_FAILED"
    HYDE_GENERATION_SUCCESS = "HYDE_GENERATION_SUCCESS"

    HYDE_RETRIEVAL_STARTED = "HYDE_RETRIEVAL_STARTED"
    HYDE_RETRIEVAL_FAILED = "HYDE_RETRIEVAL_FAILED"
    HYDE_RETRIEVAL_SUCCESS = "HYDE_RETRIEVAL_SUCCESS"

    EXITING_HYDE = "EXITING_HYDE"
    EXITING_HYDE_RETRIVER = "EXITING_HYDE_RETRIVER"
    
    HYDE_PROCESS_FAILED = "HYDE_PROCESS_FAILED"



class MultiQueryLog(BaseLogEvent):
    MULTI_QUERY_STARTED = "MULTI_QUERY_STARTED"
    MULTI_QUERY_FAILED = "MULTI_QUERY_FAILED"
    MULTI_QUERY_SUCCESS = "MULTI_QUERY_SUCCESS"


    MULTI_QUERY_RETRIEVAL_STARTED = "MULTI_QUERY_RETRIEVAL_STARTED"
    MULTI_QUERY_RETRIEVAL_FAILED = "MULTI_QUERY_RETRIEVAL_FAILED"
    MULTI_QUERY_RETRIEVAL_SUCCESS = "MULTI_QUERY_RETRIEVAL_SUCCESS"

    RRF_STARTED = "RRF_STARTED"
    RRF_FAILED = "RRF_FAILED"
    RRF_SUCCESS = "RRF_SUCCESS"

    EXITING_MULTI_QUERY = "EXITING_MULTI_QUERY"
    

class AdvancedTranslationLog(BaseLogEvent):
    ADVANCED_TRANSLATION_STARTED = "ADVANCED_TRANSLATION_STARTED"
    ADVANCED_TRANSLATION_FAILED = "ADVANCED_TRANSLATION_FAILED"
    ADVANCED_TRANSLATION_SUCCESS = "ADVANCED_TRANSLATION_SUCCESS"

    TRANSLATION_RETRIEVAL_STARTED = "TRANSLATION_RETRIEVAL_STARTED"
    TRANSLATION_RETRIEVAL_FAILED = "TRANSLATION_RETRIEVAL_FAILED"
    TRANSLATION_RETRIEVAL_SUCCESS = "TRANSLATION_RETRIEVAL_SUCCESS"

    EXITING_ADVANCED_TRANSLATION = "EXITING_ADVANCED_TRANSLATION"


class StepBackLog(BaseLogEvent):
    STEP_BACK_STARTED = "step_back_started"
    STEP_BACK_SUCCESS = "step_back_success"
    STEP_BACK_FAILED = "step_back_failed"

    STEP_BACK_RETRIEVAL_STARTED = "step_back_retrieval_started"
    STEP_BACK_RETRIEVAL_SUCCESS = "step_back_retrieval_success"
    STEP_BACK_RETRIEVAL_FAILED = "step_back_retrieval_failed"


    EXITING_STEP_BACK = "exiting_step_back"

class MultiIndexLog(BaseLogEvent):
    MULTI_INDEX_STARTED = "MULTI_INDEX_STARTED"
    MULTI_INDEX_FAILED = "MULTI_INDEX_FAILED"
    MULTI_INDEX_SUCCESS = "MULTI_INDEX_SUCCESS"

    RAW_CHUNK_RETRIEVAL_STARTED = "RAW_CHUNK_RETRIEVAL_STARTED"
    RAW_CHUNK_RETRIEVAL_FAILED = "RAW_CHUNK_RETRIEVAL_FAILED"
    RAW_CHUNK_RETRIEVAL_SUCCESS = "RAW_CHUNK_RETRIEVAL_SUCCESS"

    SUMMARY_INDEX_STARTED = "SUMMARY_INDEX_STARTED"
    SUMMARY_INDEX_FAILED = "SUMMARY_INDEX_FAILED"
    SUMMARY_INDEX_SUCCESS = "SUMMARY_INDEX_SUCCESS"

    EXPLANATION_INDEX_STARTED = "EXPLANATION_INDEX_STARTED"
    EXPLANATION_INDEX_FAILED = "EXPLANATION_INDEX_FAILED"
    EXPLANATION_INDEX_SUCCESS = "EXPLANATION_INDEX_SUCCESS"

    EXITING_MULTI_INDEX = "EXITING_MULTI_INDEX"


class QueryDecompositionLog(BaseLogEvent):
    QUERY_DECOMPOSITION_STARTED = "QUERY_DECOMPOSITION_STARTED"
    QUERY_DECOMPOSITION_FAILED = "QUERY_DECOMPOSITION_FAILED"
    QUERY_DECOMPOSITION_SUCCESS = "QUERY_DECOMPOSITION_SUCCESS"

    DECOMPOSITION_RETRIEVAL_STARTED = "DECOMPOSITION_RETRIEVAL_STARTED"
    DECOMPOSITION_RETRIEVAL_FAILED = "DECOMPOSITION_RETRIEVAL_FAILED"
    DECOMPOSITION_RETRIEVAL_SUCCESS = "DECOMPOSITION_RETRIEVAL_SUCCESS"

    EXITING_QUERY_DECOMPOSITION = "EXITING_QUERY_DECOMPOSITION"
    
    
    RRF_STARTED = "RRF_STARTED"
    RRF_FAILED = "RRF_FAILED"
    RRF_SUCCESS = "RRF_SUCCESS"


class RepairLog(BaseLogEvent):
    AI_REPAIR_INITIALIZED = "AI_REPAIR_INITIALIZED"
    AI_REPAIR_INITIALIZATION_STOPPED = "AI_REPAIR_INITIALIZATION_STOPED"

    AI_REPAIR_STARTED = "AI_REPAIR_STARTED"
    AI_REPAIR_IN_PROGRESS = "AI_REPAIR_IN_PROGRESS"
    AI_REPAIR_PREMATURELY_ENDED = "AI_REPAIR_PREMATURELY_ENDED"
    AI_REPAIR_SUCCESS = "AI_REPAIR_SUCCESS"
    AI_REPAIR_FAILED = "AI_REPAIR_FAILED"


class ProviderLog(BaseLogEvent):
    AI_PROVIDER_REQUEST = "AI_PROVIDER_REQUEST"
    AI_PROVIDER_IN_PROCESSING = "AI_PROVIDER_IN_PROCESSING"
    AI_PROVIDER_SUCCESS = "AI_PROVIDER_SUCCESS"
    AI_PROVIDER_FAILURE = "AI_PROVIDER_FAILURE"


class DatabaseLog(BaseLogEvent):
    DB_COMMIT = "DB_COMMIT"
    DB_ROLLBACK = "DB_ROLLBACK"
    DB_ERROR = "DB_ERROR"


class ExceptionLog(BaseLogEvent):
    # General / Application
    APP_EXCEPTION = "APP_EXCEPTION"
    UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION"

    # Services
    AI_SERVICE_EXCEPTION = "AI_SERVICE_EXCEPTION"
    POSTING_SERVICE_EXCEPTION = "POSTING_SERVICE_EXCEPTION"

    # Auth & Account
    LOGIN_EXCEPTION = "LOGIN_EXCEPTION"
    LOGOUT_EXCEPTION = "LOGOUT_EXCEPTION"
    LOGOUT_ALL_DEVICES_EXCEPTION = "LOGOUT_ALL_DEVICES_EXCEPTION"
    PASSWORD_CHANGE_EXCEPTION = "PASSWORD_CHANGE_EXCEPTION"
    USER_CREATION_EXCEPTION = "USER_CREATION_EXCEPTION"
    ACTIVE_SESSION_COUNT_EXCEPTION = "ACTIVE_SESSION_COUNT_EXCEPTION"
    REVOKATION_CURRENT_SESSION_EXCEPTION = "REVOKATION_CURRENT_SESSION_EXCEPTION"
    LIKE_EXCEPTION = "LIKE_EXCEPTION"

    # Document & RAG Pipeline Processing
    FILE_UPLADONG_EXCEPTION = "FILE_UPLADONG_EXCEPTION"
    VALIDATED_FILE_SAVING_EXCEPTION = "VALIDATED_FILE_SAVING_EXCEPTION"
    SAVING_VALIDATED_FILE_EXCEPTION = "SAVING_VALIDATED_FILE_EXCEPTION"
    PARSING_SAVED_FILE_EXCEPTION = "PARSING_SAVED_FILE_EXCEPTION"
    CHUNKING_PARSE_DOC_EXCEPTION = "CHUNKING_PARSE_DOC_EXCEPTION"
    EMBEDDING_CHUNKS_EXCEPTION = "EMBEDDING_CHUNKS_EXCEPTION"
    TOKENIZATION_EXCEPTION = "TOKENIZATION_EXCEPTION"
    MISSING_DOCUMENT_EXCEPTION = "MISSING_DOCUMENT_EXCEPTION"
    INVALID_TASK1_PAYLOAD_EXCEPTION = "INVALID_TASK1_PAYLOAD_EXCEPTION"
    INVALID_TASK2_PAYLOAD_EXCEPTION = "INVALID_TASK2_PAYLOAD_EXCEPTION"
    
    
    #vector database:
    MISSING_VECTOR_DATABASE_EXCEPTION = "MISSING_VECTOR_DATABASE_EXCEPTION"
    NO_RELATED_VECTOR_DATABASE_FOUND = "NO_RELATED_VECTOR_DATABASE_FOUND"  


class SecurityLog(BaseLogEvent):
    PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"
    INAPPROPRIATE_CONTENT_DETECTED = "INAPPROPRIATE_CONTENT_DETECTED"
    UNKNOWN_INPUT = "UNKNOWN_INPUT"
    EMPTY_INPUT = "EMPTY_INPUT"
    UNSUPPORTED_INPUT = "UNSUPPORTED_INPUT"


class PostingLogs(BaseLogEvent):
    # Service lifecycle
    POSTING_SERVICE_STARTED = "POSTING_SERVICE_STARTED"
    EXITING_POSTING_SERVICE = "EXITING_POSTING_SERVICE"

    # Posts
    FETCHING_POSTS = "FETCHING_POSTS"
    FETCHING_POST = "FETCHING_POST"
    CREATING_POST = "CREATING_POST"
    UPDATING_POST = "UPDATING_POST"
    DELETING_POST = "DELETING_POST"

    # Comments
    FETCHING_COMMENTS = "FETCHING_COMMENTS"
    CREATING_COMMENT = "CREATING_COMMENT"
    DELETING_COMMENT = "DELETING_COMMENT"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"




class QuestionLogs(BaseLogEvent):
    # Lifecycle
    QUESTION_ROUTE_STARTED = "QUESTION_ROUTE_STARTED"
    EXITING_QUESTION_ROUTE = "EXITING_QUESTION_SERVICE"

    # Vector DB Resolution
    GETTING_USER_VDB = "GETTING_USER_VDB"
    FETCHING_COLLECTION_NAME = "FETCHING_COLLECTION_NAME"
    VDB_INITIALIZED = "VDB_INITIALIZED"
    VDB_NOT_FOUND = "VDB_NOT_FOUND"
    VDB_FOUND = "VDB_FOUND"

    # Processing
    INVOKING_AI_SERVICE = "INVOKING_AI_SERVICE"
    PROCESSING_STRATEGY = "PROCESSING_STRATEGY"
    
    # Validation
    VALIDATING_USER_JWT = "VALIDATING_USER_JWT"
    RATE_LIMIT_CHECK = "RATE_LIMIT_CHECK"

    # Result
    QUESTION_SUCCESS = "QUESTION_SUCCESS"
    QUESTION_FAILED = "QUESTION_FAILED"
    
    CHECKING_USER_VDB = "CHECKING_USER_VDB"

    # NEW LOG STATES FOR CACHING & INTENT (surface route)
    CHECKING_CONVO_INTENT = "CHECKING_CONVO_INTENT"
    CONVO_INTENT_CONTINUE = "CONVO_INTENT_CONTINUE"
    CHECKING_MULTI_TIER_CACHE = "CHECKING_MULTI_TIER_CACHE"
    CACHE_HIT_SUCCESS = "CACHE_HIT_SUCCESS"
    CACHE_MISS_FALLTHROUGH = "CACHE_MISS_FALLTHROUGH"
    BACKGROUND_CACHE_POPULATION_FIRED = "BACKGROUND_CACHE_POPULATION_FIRED"
    SERVICE_FAILED = "SERVICE_FAILED"
    
    # NEW LOG STATES FOR CACHE VDB INITIATOR 
    CACHE_VDB_CHECKING_RESOURCE = "CACHE_VDB_CHECKING_RESOURCE"
    CACHE_VDB_CREATING_PENDING = "CACHE_VDB_CREATING_PENDING"
    CACHE_VDB_STATUS_SKIPPED = "CACHE_VDB_STATUS_SKIPPED"
    CACHE_VDB_LOCKED_PROCESSING = "CACHE_VDB_LOCKED_PROCESSING"
    CACHE_VDB_WORKER_FIRED = "CACHE_VDB_WORKER_FIRED"
    
    #NEW LOG STATES FOR CELERY CACHE VDB WORKER for cache vdb creation
    CELERY_TASK_STARTED = "CELERY_TASK_STARTED"
    CELERY_TASK_RETRYING = "CELERY_TASK_RETRYING"
    CACHE_VDB_DIR_CREATING = "CACHE_VDB_DIR_CREATING"
    CACHE_VDB_STORE_INITIALIZING = "CACHE_VDB_STORE_INITIALIZING"
    CACHE_VDB_MARKED_READY = "CACHE_VDB_MARKED_READY"
    CACHE_VDB_MARKED_FAILED = "CACHE_VDB_MARKED_FAILED"
    
    
    #cacheing system!
    CACHE_TIER1_EXACT_HIT = "CACHE_TIER1_EXACT_HIT"
    CACHE_CLASSIFICATION_AI = "CACHE_CLASSIFICATION_AI"
    CACHE_POLICY_NON_CACHEABLE = "CACHE_POLICY_NON_CACHEABLE"
    CACHE_POLICY_CACHEABLE = "CACHE_POLICY_CACHEABLE"
    CACHE_TIER2_VECTOR_HIT = "CACHE_TIER2_VECTOR_HIT"
    CACHE_TIER3_CHROMA_HIT = "CACHE_TIER3_CHROMA_HIT"
    CACHE_SYSTEM_MISS_FALLBACK = "CACHE_SYSTEM_MISS_FALLBACK"
    
    
    #NEW LOG STATES FOR GET REDIS VECTOR CACHED 
    REDIS_VECTOR_SEARCH_STARTED = "REDIS_VECTOR_SEARCH_STARTED"
    REDIS_VECTOR_HIT_FOUND = "REDIS_VECTOR_HIT_FOUND"
    REDIS_VECTOR_SCORE_MISMATCH = "REDIS_VECTOR_SCORE_MISMATCH"
    REDIS_VECTOR_INCOMING_PROVENANCE_MISSING = "REDIS_VECTOR_INCOMING_PROVENANCE_MISSING" #meaning incoming vector didnt has dict[doc_id, latest_version]
    REDIS_VECTOR_STORED_PROVENANCE_MISSING = "REDIS_VECTOR_STORED_PROVENANCE_MISSING "#meaning stored vector didnt had dict[doc_id, latest_version]
    REDIS_VECTOR_VERSION_MISMATCH = "REDIS_VECTOR_VERSION_MISMATCH"
    REDIS_VECTOR_CACHE_MISS = "REDIS_VECTOR_CACHE_MISS"
    REDIS_VECTOR_ERROR = "REDIS_VECTOR_ERROR"
    REDIS_VECTOR_GENERATING_EMBEDDING = "REDIS_VECTOR_GENERATING_EMBEDDING"
    REDIS_VECTOR_SCOPE_NORMALIZED = "REDIS_VECTOR_SCOPE_NORMALIZED"
    REDIS_VECTOR_QUERY_EXECUTING = "REDIS_VECTOR_QUERY_EXECUTING"
    
    #NEW LOG STATES FOR GET_CACHED (TIER 3 CHROMA)
    CHROMA_SIMILARITY_SEARCH_STARTED = "CHROMA_SIMILARITY_SEARCH_STARTED"
    CHROMA_SIMILARITY_SEARCH_ERROR = "CHROMA_SIMILARITY_SEARCH_ERROR"
    CHROMA_CANDIDATES_NOT_FOUND = "CHROMA_CANDIDATES_NOT_FOUND"
    CHROMA_BATCH_VERSION_FETCH = "CHROMA_BATCH_VERSION_FETCH"
    CHROMA_VALID_CANDIDATES_FOUND = "CHROMA_VALID_CANDIDATES_FOUND"
    CHROMA_NO_VALID_CANDIDATES = "CHROMA_NO_VALID_CANDIDATES"
    CHROMA_RERANK_STARTED = "CHROMA_RERANK_STARTED"
    CHROMA_RERANK_FAILED = "CHROMA_RERANK_FAILED"
    CHROMA_RELEVANCE_THRESHOLD_FAILED = "CHROMA_RELEVANCE_THRESHOLD_FAILED"
    CHROMA_DELIBERATE_MISS_TRIGGERED = "CHROMA_DELIBERATE_MISS_TRIGGERED"
    CHROMA_CACHE_HIT = "CHROMA_CACHE_HIT"
    
    
    #NEW LOG STATES FOR SAVE TO REDIS VECTOR CACHE 
    REDIS_VECTOR_SAVE_STARTED = "REDIS_VECTOR_SAVE_STARTED"
    REDIS_VECTOR_INDEX_ENSURED = "REDIS_VECTOR_INDEX_ENSURED"
    REDIS_VECTOR_EMBEDDING_GENERATED = "REDIS_VECTOR_EMBEDDING_GENERATED"
    REDIS_VECTOR_PAYLOAD_SERIALIZED = "REDIS_VECTOR_PAYLOAD_SERIALIZED"
    REDIS_VECTOR_HASH_SAVED = "REDIS_VECTOR_HASH_SAVED"
    REDIS_VECTOR_TTL_SET = "REDIS_VECTOR_TTL_SET"
    REDIS_VECTOR_SAVE_ERROR = "REDIS_VECTOR_SAVE_ERROR"
    
    
    #NEW LOG STATES FOR CREATE REDIS VECTOR INDEX
    REDIS_INDEX_CHECK_STARTED = "REDIS_INDEX_CHECK_STARTED"
    REDIS_INDEX_EXISTS_CACHED = "REDIS_INDEX_EXISTS_CACHED"
    REDIS_INDEX_CREATION_STARTED = "REDIS_INDEX_CREATION_STARTED"
    REDIS_INDEX_ALREADY_EXISTS = "REDIS_INDEX_ALREADY_EXISTS"
    REDIS_INDEX_CREATED_SUCCESS = "REDIS_INDEX_CREATED_SUCCESS"
    REDIS_INDEX_CREATION_ERROR = "REDIS_INDEX_CREATION_ERROR"
    REDIS_INDEX_INITIALIZATION_COMPLETE = "REDIS_INDEX_INITIALIZATION_COMPLETE"
    
    
    #mine additional
    CACHE_VDB_NOT_FOUND = "CACHE_VDB_NOT_FOUND"
    CACHE_VDB_PUSH_ASYNC_ENTERED = "CACHE_VDB_PUSH_ASYNC_ENTERED"

class UploadFileLogs(BaseLogEvent):
    # Lifecycle
    UPLOAD_SERVICE_STARTED = "UPLOAD_SERVICE_STARTED"
    EXITING_UPLOAD_SERVICE = "EXITING_UPLOAD_SERVICE"

    # Validation
    VALIDATING_FILE = "VALIDATING_FILE"
    VALIDATION_SUCCESS = "VALIDATION_SUCCESS"
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # Worker & Processing
    INITIATING_WORKER = "INITIATING_WORKER"
    WORKER_INITIATED_SUCCESS = "WORKER_INITIATED_SUCCESS"

    # Result
    UPLOAD_SUCCESS = "UPLOAD_SUCCESS"
    UPLOAD_FAILED = "UPLOAD_FAILED"

    # Validation Service Steps
    VALIDATION_SERVICE_STARTED = "VALIDATION_SERVICE_STARTED"
    CHECKING_FILENAME = "CHECKING_FILENAME"
    CHECKING_EXTENSION = "CHECKING_EXTENSION"
    CHECKING_MIME_TYPE = "CHECKING_MIME_TYPE"
    READING_FILE_BYTES = "READING_FILE_BYTES"
    VALIDATING_MAGIC_BYTES = "VALIDATING_MAGIC_BYTES"
    CHECKING_DUPLICATE_HASH = "CHECKING_DUPLICATE_HASH"
    CONSTRUCTING_PAYLOAD = "CONSTRUCTING_PAYLOAD"
    VALIDATION_SERVICE_SUCCESS = "VALIDATION_SERVICE_SUCCESS"
    VALIDATION_SERVICE_FAILURE = "VALIDATION_SERVICE_FAILURE"
    EXITING_VALIDATION_SERVICE = "EXITING_VALIDATION_SERVICE"

    # Detailed Worker Initiator States
    WORKER_SKIPPED_DOC_NOT_READY = "WORKER_SKIPPED_DOC_NOT_READY"
    WORKER_SKIPPED_BOTH_READY = "WORKER_SKIPPED_BOTH_READY"
    WORKER_SKIPPED_ALREADY_PROCESSING = "WORKER_SKIPPED_ALREADY_PROCESSING"
    WORKER_SKIPPED_NONE_NEEDED = "WORKER_SKIPPED_NONE_NEEDED"
    QUEUING_MULTI_INDEX_TASK_INISHIATOR = "QUEUING_MULTI_INDEX_TASK_INISHIATOR"

    # Background Worker Execution States
    MULTI_INDEX_TASK_STARTED = "MULTI_INDEX_TASK_STARTED"
    FETCHING_RAW_CHUNKS = "FETCHING_RAW_CHUNKS"
    BUILDING_SUMMARY_VDB = "BUILDING_SUMMARY_VDB"
    SUMMARY_VDB_SUCCESS = "SUMMARY_VDB_SUCCESS"
    SUMMARY_VDB_FAILED = "SUMMARY_VDB_FAILED"
    BUILDING_EXPLANATION_VDB = "BUILDING_EXPLANATION_VDB"
    EXPLANATION_VDB_SUCCESS = "EXPLANATION_VDB_SUCCESS"
    EXPLANATION_VDB_FAILED = "EXPLANATION_VDB_FAILED"
    MULTI_INDEX_TASK_COMPLETED = "MULTI_INDEX_TASK_COMPLETED"
    FETCHING_DOCUMENT_FOR_TASK = "FETCHING_DOCUMENT_FOR_TASK"
    
    
    # Task 1 & Task 2 Execution States
    SAVE_TASK_STARTED = "SAVE_TASK_STARTED"
    VALIDATING_TASK_PAYLOAD = "VALIDATING_TASK_PAYLOAD"
    SAVING_DOC_TO_DB = "SAVING_DOC_TO_DB"
    INITIATING_TASK_2 = "INITIATING_TASK_2"
    TASK_2_INITIATED_SUCCESS = "TASK_2_INITIATED_SUCCESS"
    TASK_2_INITIATION_FAILED = "TASK_2_INITIATION_FAILED"
    TASK_VALIDATION_ERROR = "TASK_VALIDATION_ERROR"
    TASK_RETRYING = "TASK_RETRYING"
    SAVE_TASK1_ASYNC_STARTED = "SAVE_TASK1_ASYNC_STARTED"
    SAVE_TASK1_ASYNC_SUCCESS = "SAVE_TASK1_ASYNC_SUCCESS"
    
    
    # Save Service Steps
    SAVE_SERVICE_STARTED = "SAVE_SERVICE_STARTED"
    WRITING_FILE_TO_DISK = "WRITING_FILE_TO_DISK"
    COMMITTING_DOC_TO_DB = "COMMITTING_DOC_TO_DB"
    VALIDATING_SAVED_DOC_ORM = "VALIDATING_SAVED_DOC_ORM"
    SAVE_SERVICE_SUCCESS = "SAVE_SERVICE_SUCCESS"
    SAVE_SERVICE_FAILED_ROLLING_BACK = "SAVE_SERVICE_FAILED_ROLLING_BACK"
    
    
    
    # Task 2 Execution States
    TASK_2_STARTED = "TASK_2_STARTED"
    VALIDATING_TASK_2_PAYLOAD = "VALIDATING_TASK_2_PAYLOAD"
    RUNNING_TASK_2_ASYNC = "RUNNING_TASK_2_ASYNC"
    TASK_2_SUCCESS = "TASK_2_SUCCESS"
    TASK_2_VALIDATION_ERROR = "TASK_2_VALIDATION_ERROR"
    TASK_2_RETRYING = "TASK_2_RETRYING"
    
    
    
    # Task 2 Async Wrapper States
    TASK_2_ASYNC_STARTED = "TASK_2_ASYNC_STARTED"
    TASK_2_ASYNC_SUCCESS = "TASK_2_ASYNC_SUCCESS"
    
    
    # Task 2 Service & Pipeline States
    TASK_2_SERVICE_STARTED = "TASK_2_SERVICE_STARTED"
    DOCUMENT_NOT_FOUND_IN_SERVICE = "DOCUMENT_NOT_FOUND_IN_SERVICE"
    PARSING_STAGE_STARTED = "PARSING_STAGE_STARTED"
    PARSING_STAGE_SUCCESS = "PARSING_STAGE_SUCCESS"
    PARSING_STAGE_FAILED = "PARSING_STAGE_FAILED"
    CHUNKING_STAGE_STARTED = "CHUNKING_STAGE_STARTED"
    CHUNKING_STAGE_SUCCESS = "CHUNKING_STAGE_SUCCESS"
    CHUNKING_STAGE_FAILED = "CHUNKING_STAGE_FAILED"
    EMBEDDING_STAGE_STARTED = "EMBEDDING_STAGE_STARTED"
    EMBEDDING_STAGE_SUCCESS = "EMBEDDING_STAGE_SUCCESS"
    EMBEDDING_STAGE_FAILED = "EMBEDDING_STAGE_FAILED"
    TASK_2_SERVICE_SUCCESS = "TASK_2_SERVICE_SUCCESS"
    FAILED_CASE_TRIGGERED = "FAILED_CASE_TRIGGERED"
    
    
    # Polling Endpoint States
    POLL_WORKER_REQUESTED = "POLL_WORKER_REQUESTED"
    INITIATING_MULTI_INDEX_CHECK = "INITIATING_MULTI_INDEX_CHECK"
    REFRESHING_DOCUMENT_STATUS = "REFRESHING_DOCUMENT_STATUS"
    POLL_WORKER_SUCCESS = "POLL_WORKER_SUCCESS"
    
    
    # Polling & Status Service States
    REDIS_AND_DB_STATUS_CHECK_STARTED = "REDIS_AND_DB_STATUS_CHECK_STARTED"
    REDIS_AND_DB_STATUS_CHECK_SUCCESS = "REDIS_AND_DB_STATUS_CHECK_SUCCESS"
    CHECKING_REDIS_WORKER_STATE = "CHECKING_REDIS_WORKER_STATE"
    REDIS_WORKER_SUCCESS = "REDIS_WORKER_SUCCESS"
    REDIS_WORKER_FAILED = "REDIS_WORKER_FAILED"
    REDIS_WORKER_RETRYING = "REDIS_WORKER_RETRYING"
    REDIS_WORKER_PROCESSING = "REDIS_WORKER_PROCESSING"
    FETCHING_DOCUMENT_BY_REQUEST_ID = "FETCHING_DOCUMENT_BY_REQUEST_ID"
    DOCUMENT_PENDING_SAVE_STATE = "DOCUMENT_PENDING_SAVE_STATE"
    DOCUMENT_FOUND_STATE = "DOCUMENT_FOUND_STATE"
    
    
    
    #bm25 task:
    CHECKING_BM25_STATUS = "CHECKING_BM25_STATUS"
    BM25_STATUS_FETCHED_SUCCESS = "BM25_STATUS_FETCHED_SUCCESS"
    BM25_STATUS_PENDING_INIT = "BM25_STATUS_PENDING_INIT"
    QUEUING_BM25_TASK_INITIATOR = "QUEUING_BM25_TASK_INITIATOR"
    BUILDING_GLOBAL_BM25 = "BUILDING_GLOBAL_BM25"


class AuthLogs(BaseLogEvent):
    # Service lifecycle
    AUTH_SERVICE_STARTED = "AUTH_SERVICE_STARTED"
    EXITING_AUTH_SERVICE = "EXITING_AUTH_SERVICE"

    # Authentication
    AUTHENTICATING_USER = "AUTHENTICATING_USER"
    REGISTERING_USER = "REGISTERING_USER"
    VERIFYING_TOKEN = "VERIFYING_TOKEN"
    REFRESHING_TOKEN = "REFRESHING_TOKEN"
    LOGGING_OUT_USER = "LOGGING_OUT_USER"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"
    VALIDATING_SESSION = "VALIDATING_SESSION"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Redis & Session Store
    CONNECTING_TO_REDIS = "CONNECTING_TO_REDIS"
    CACHING_JWT_SESSION = "CACHING_JWT_SESSION"
    CHECKING_JWT_SESSION = "CHECKING_JWT_SESSION"
    DELETING_JWT_SESSION = "DELETING_JWT_SESSION"

    # Session Management
    CREATING_SESSION = "CREATING_SESSION"
    SESSION_CREATED = "SESSION_CREATED"
    CHECKING_SESSION = "CHECKING_SESSION"
    SESSION_FOUND = "SESSION_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    CHECKING_ALL_SESSIONS = "CHECKING_ALL_SESSIONS"
    SESSIONS_FOUND = "SESSIONS_FOUND"
    NO_SESSION_FOUND = "NO_SESSION_FOUND"
    DELETING_SESSION = "DELETING_SESSION"
    SESSION_DELETED = "SESSION_DELETED"
    SESSION_ALREADY_DELETED = "SESSION_ALREADY_DELETED"
    DELETING_ALL_SESSIONS = "DELETING_ALL_SESSIONS"
    ALL_SESSIONS_DELETED = "ALL_SESSIONS_DELETED"
    SESSIONS_ALREADY_DELETED = "SESSIONS_ALREADY_DELETED"
    COUNTING_ACTIVE_SESSIONS = "COUNTING_ACTIVE_SESSIONS"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class LikeLogs(BaseLogEvent):
    # Service lifecycle
    LIKE_SERVICE_STARTED = "LIKE_SERVICE_STARTED"
    EXITING_LIKE_SERVICE = "EXITING_LIKE_SERVICE"

    # Actions
    LIKING_POST = "LIKING_POST"
    UNLIKING_POST = "UNLIKING_POST"
    FETCHING_USER_LIKES = "FETCHING_USER_LIKES"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"


class UserLogs(BaseLogEvent):
    # Service lifecycle
    USER_SERVICE_STARTED = "USER_SERVICE_STARTED"
    EXITING_USER_SERVICE = "EXITING_USER_SERVICE"

    # CRUD
    FETCHING_USERS = "FETCHING_USERS"
    FETCHING_USER = "FETCHING_USER"
    CREATING_USER = "CREATING_USER"
    UPDATING_USER = "UPDATING_USER"
    DELETING_USER = "DELETING_USER"

    # Validation / Authorization
    VALIDATING_REQUEST = "VALIDATING_REQUEST"
    AUTHORIZATION_CHECK = "AUTHORIZATION_CHECK"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"

    # Database
    EXECUTING_DATABASE_QUERY = "EXECUTING_DATABASE_QUERY"
    UPDATING_DATABASE = "UPDATING_DATABASE"

    # Result
    SUCCESS = "SUCCESS"
    OPERATION_FAILED = "OPERATION_FAILED"